### ISSUE TITLE
Rune Solver

### ISSUE THREAD

**Issue by Nitai-Shavit** [trankevint/maple-bot#5]
If i'm only intrested in the rune solver, i want it to solve it for me everytime it pops up, how'd i go to make it?

**Comment by Nitai-Shavit** [comment]
Aswell i get this error whenever i try to run it. maybe I'm missing something
Traceback (most recent call last):
  File "c:\Users\...\Maplestory\RuneSolver\maplebotmaster\maple-bot-master\main.py", line 61, in <module>
    c = interception()
  File "c:\Users\...\Maplestory\RuneSolver\maplebotmaster\maple-bot-master\interception\interception.py", line 28, in __init__
    raise e
  File "c:\Users\...\Maplestory\RuneSolver\maplebotmaster\maple-bot-master\interception\interception.py", line 19, in __init__
    _device = device(k32.CreateFileA(b'\\\\.\\interception%02d' % i,
  File "c:\Users\...\Maplestory\RuneSolver\maplebotmaster\maple-bot-master\interception\interception.py", line 118, in __init__
    raise Exception("Can't create device")
Exception: Can't create device

**Comment by qlvbrknp** [comment]
Hi Nitai-Shavit,

If you want to repurpose the portion of the code that solve runes, it is located in `rune_solver.py` and `main.py`.
